import Footer from "@/app/components/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import NavBar from "./components/NavBar/views/NavBar";
import TwoBttnsNavBar from "./components/NavBar/containers/TwoBttnsNavBar";
import Link from "next/link";
import { previewLinkCards } from "./components/PreviewLinkCard/containers/PreviewLinkCardsHome";
import { PreviewLinkCardProps } from "./components/PreviewLinkCard/views/PreviewLinkCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type SidebarNavItems = {
  key: string;
  content?: React.ReactNode;
  link?: string;
  external?: boolean;
  type?: "link" | "heading" | "divider";
};

export const navBarItems: SidebarNavItems[] = [
  {
    key: "brand-2bttns",
    content: <div className="font-extrabold text-xl">2bttns</div>,
    link: "/",
  },
  {
    key: "home",
    content: "Home",
    link: "/",
  },
  {
    key: "divider-1",
    type: "divider",
  },
  {
    key: "heading-1",
    content: "Manage",
    type: "heading",
  },
  {
    key: "games",
    content: "Games",
    link: "/games",
  },
  {
    key: "tags",
    content: "Tags",
    link: "/tags",
  },
  {
    key: "game-objects",
    content: "Game Objects",
    link: "/game-objects",
  },
  {
    key: "divider-2",
    type: "divider",
  },
  {
    key: "settings",
    content: "Settings",
    link: "/settings",
  },
  {
    key: "divider-3",
    content: "Documentation",
    link: "https://docs.2bttns.com",
    external: true,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <>
            <div className="drawer lg:drawer-open">
              <input
                id="2bttns-layout-drawer"
                type="checkbox"
                className="drawer-toggle"
              />
              <div className="drawer-content flex flex-col items-center justify-center ml-80">
                <div className="sticky top-0 self-end">
                  <TwoBttnsNavBar />
                </div>
                <main className="flex min-h-screen flex-col items-center justify-between p-24">
                  {children}
                </main>
                <Footer />
                <label
                  htmlFor="2bttns-layout-drawer"
                  className="btn btn-primary drawer-button lg:hidden"
                >
                  Open drawer
                </label>
              </div>
              <div className="drawer-side position">
                <label
                  htmlFor="2bttns-layout-drawer"
                  aria-label="close sidebar"
                  className="drawer-overlay"
                ></label>
                <ul className="menu bg-base-200 text-base-content min-h-full w-80 p-4 fixed">
                  {navBarItems.map((item) => {
                    if (item.type === "divider") {
                      return <div key={item.key} className="divider"></div>;
                    }

                    if (item.type === "heading") {
                      return (
                        <li key={item.key} className="font-bold text-md ml-3">
                          {item.content}
                        </li>
                      );
                    }

                    return (
                      <li key={item.key}>
                        <Link
                          href={item.link ?? "#"}
                          target={item.external ? "_blank" : "_self"}
                        >
                          {item.content} {item.external ? "↗" : ""}
                        </Link>
                      </li>
                    );
                  })}
                </ul>
              </div>
            </div>
          </>
        </body>
      </Providers>
    </html>
  );
}
